"""
Curated offline bright-star rows for plate-solve annotations (RA/Dec J2000, degrees).

Used by CamGUI after local plate solve when network object lookup is unavailable.
"""

from __future__ import annotations

# Each entry: name, J2000 RA/Dec, human-readable source tag, one-line fact.
OFFLINE_STAR_FACTS: list[dict] = [
    # --- Original Hipparcos-tagged bright set ---
    {"name": "Sirius", "ra_deg": 101.287155, "dec_deg": -16.716116, "source": "Hipparcos", "fact": "Sirius is the brightest star in Earth's night sky and is a binary system."},
    {"name": "Canopus", "ra_deg": 95.987958, "dec_deg": -52.695661, "source": "Hipparcos", "fact": "Canopus is a luminous supergiant and the second-brightest night-sky star."},
    {"name": "Arcturus", "ra_deg": 213.915300, "dec_deg": 19.182410, "source": "Hipparcos", "fact": "Arcturus is a nearby orange giant and one of the brightest stars in the northern sky."},
    {"name": "Vega", "ra_deg": 279.234734, "dec_deg": 38.783688, "source": "Hipparcos", "fact": "Vega was the North Star about 12,000 years ago and will be again in the far future."},
    {"name": "Capella", "ra_deg": 79.172327, "dec_deg": 45.997991, "source": "Hipparcos", "fact": "Capella appears as one bright point but is actually a multiple-star system."},
    {"name": "Rigel", "ra_deg": 78.634467, "dec_deg": -8.201639, "source": "Hipparcos", "fact": "Rigel is a blue supergiant in Orion and vastly more luminous than the Sun."},
    {"name": "Procyon", "ra_deg": 114.825493, "dec_deg": 5.224993, "source": "Hipparcos", "fact": "Procyon has a white-dwarf companion and forms the Winter Triangle with Sirius and Betelgeuse."},
    {"name": "Betelgeuse", "ra_deg": 88.792939, "dec_deg": 7.407064, "source": "Hipparcos", "fact": "Betelgeuse is a red supergiant nearing the end of its stellar life."},
    {"name": "Altair", "ra_deg": 297.695828, "dec_deg": 8.868322, "source": "Hipparcos", "fact": "Altair rotates so quickly that it is noticeably flattened at the poles."},
    {"name": "Aldebaran", "ra_deg": 68.980163, "dec_deg": 16.509302, "source": "Hipparcos", "fact": "Aldebaran is an orange giant that marks the eye of Taurus."},
    {"name": "Antares", "ra_deg": 247.351915, "dec_deg": -26.432002, "source": "Hipparcos", "fact": "Antares is a massive red supergiant and one of the brightest stars in Scorpius."},
    {"name": "Spica", "ra_deg": 201.298247, "dec_deg": -11.161322, "source": "Hipparcos", "fact": "Spica is a close binary whose stars are so near they distort each other."},
    {"name": "Pollux", "ra_deg": 116.328958, "dec_deg": 28.026183, "source": "Hipparcos", "fact": "Pollux is a giant star known to host at least one confirmed exoplanet."},
    {"name": "Fomalhaut", "ra_deg": 344.412750, "dec_deg": -29.622236, "source": "Hipparcos", "fact": "Fomalhaut is surrounded by a prominent debris disk studied in exoplanet imaging."},
    {"name": "Deneb", "ra_deg": 310.357979, "dec_deg": 45.280339, "source": "Hipparcos", "fact": "Deneb is an extremely luminous supergiant and part of the Summer Triangle."},
    {"name": "Regulus", "ra_deg": 152.092962, "dec_deg": 11.967208, "source": "Hipparcos", "fact": "Regulus spins rapidly and is a multiple-star system in Leo."},
    {"name": "Polaris", "ra_deg": 37.954561, "dec_deg": 89.264109, "source": "Hipparcos", "fact": "Polaris is a Cepheid variable and sits close to the north celestial pole."},
    # --- Additional 1st-magnitude-class and common navigation stars (literature distances in ly) ---
    {"name": "Achernar", "ra_deg": 24.428611, "dec_deg": -57.236753, "source": "Hipparcos", "fact": "Achernar is a hot, rapidly spinning Be star and the brightest star in Eridanus (~139 ly)."},
    {"name": "Hadar", "ra_deg": 210.955833, "dec_deg": -60.373056, "source": "Hipparcos", "fact": "Hadar (Beta Centauri) is a binary system and one of the brightest stars in Centaurus (~390 ly)."},
    {"name": "Acrux", "ra_deg": 186.649563, "dec_deg": -63.099092, "source": "Hipparcos", "fact": "Acrux is the brightest star in Crux and a multiple system (~321 ly)."},
    {"name": "Adhara", "ra_deg": 104.656453, "dec_deg": -28.972086, "source": "Hipparcos", "fact": "Adhara (Epsilon Canis Majoris) is a hot supergiant in Canis Major (~430 ly)."},
    {"name": "Shaula", "ra_deg": 263.402167, "dec_deg": -37.103824, "source": "Hipparcos", "fact": "Shaula (Lambda Scorpii) is a massive binary dominating the tail of Scorpius (~570 ly)."},
    {"name": "Castor", "ra_deg": 113.649345, "dec_deg": 31.888282, "source": "Hipparcos", "fact": "Castor is a famous sextuple-star system in Gemini (~51.6 ly)."},
    {"name": "Gacrux", "ra_deg": 187.791498, "dec_deg": -57.113214, "source": "Hipparcos", "fact": "Gacrux (Gamma Crucis) is a red giant at the top of the Southern Cross (~88.6 ly)."},
    {"name": "Bellatrix", "ra_deg": 81.282764, "dec_deg": 6.349703, "source": "Hipparcos", "fact": "Bellatrix is a hot B giant marking Orion's eastern shoulder (~250 ly)."},
    {"name": "Elnath", "ra_deg": 81.572971, "dec_deg": 28.607451, "source": "Hipparcos", "fact": "Elnath (Beta Tauri) is a B giant shared between Taurus and Auriga (~131 ly)."},
    {"name": "Miaplacidus", "ra_deg": 138.300833, "dec_deg": -69.717222, "source": "Hipparcos", "fact": "Miaplacidus is the second-brightest star in Carina and a common southern navigation star (~111 ly)."},
    {"name": "Alnilam", "ra_deg": 84.053389, "dec_deg": -1.201917, "source": "Hipparcos", "fact": "Alnilam is the central star in Orion's Belt and a distant blue supergiant (~1340 ly)."},
    {"name": "Alnair", "ra_deg": 332.058271, "dec_deg": -46.960975, "source": "Hipparcos", "fact": "Alnair (Alpha Gruis) is the brightest star in Grus (~101 ly)."},
    {"name": "Alioth", "ra_deg": 193.507292, "dec_deg": 55.959822, "source": "Hipparcos", "fact": "Alioth is the brightest star in the Big Dipper asterism (~82.6 ly)."},
    {"name": "Alnitak", "ra_deg": 85.189694, "dec_deg": -1.942572, "source": "Hipparcos", "fact": "Alnitak is the easternmost belt star in Orion and a tight binary (~736 ly)."},
    {"name": "Alphard", "ra_deg": 141.896831, "dec_deg": -8.658602, "source": "Hipparcos", "fact": "Alphard (Alpha Hydrae) is an orange giant marking the heart of the long Hydra chain."},
    {"name": "Alkaid", "ra_deg": 206.885157, "dec_deg": 49.313267, "source": "Hipparcos", "fact": "Alkaid is the star at the end of the Big Dipper's handle in Ursa Major."},
    {"name": "Dubhe", "ra_deg": 165.931964, "dec_deg": 61.751339, "source": "Hipparcos", "fact": "Dubhe is the northern pointer star of the Big Dipper and a spectroscopic binary."},
    {"name": "Merak", "ra_deg": 165.460314, "dec_deg": 56.382351, "source": "Hipparcos", "fact": "Merak with Dubhe points toward Polaris along the celestial sphere."},
    {"name": "Phecda", "ra_deg": 178.457698, "dec_deg": 53.694993, "source": "Hipparcos", "fact": "Phecda (Gamma Ursae Majoris) forms part of the Big Dipper bowl."},
    {"name": "Megrez", "ra_deg": 183.856507, "dec_deg": 57.032597, "source": "Hipparcos", "fact": "Megrez is the faintest of the seven Dipper stars but still a naked-eye landmark."},
    {"name": "Mizar", "ra_deg": 200.981250, "dec_deg": 54.925361, "source": "Hipparcos", "fact": "Mizar and Alcor are a classic naked-eye double in Ursa Major."},
    {"name": "Mirach", "ra_deg": 10.190424, "dec_deg": 35.620442, "source": "Hipparcos", "fact": "Mirach in Andromeda is often used as a hop star toward the Andromeda Galaxy."},
    {"name": "Schedar", "ra_deg": 10.126774, "dec_deg": 56.537331, "source": "Hipparcos", "fact": "Schedar (Alpha Cassiopeiae) is an orange giant in the distinctive W of Cassiopeia."},
    {"name": "Algol", "ra_deg": 47.042218, "dec_deg": 40.955661, "source": "Hipparcos", "fact": "Algol is the prototype eclipsing binary and was once called the 'Demon Star'."},
    {"name": "Hamal", "ra_deg": 31.793357, "dec_deg": 23.462493, "source": "Hipparcos", "fact": "Hamal is the brightest star in Aries and an evolved orange giant."},
    {"name": "Markab", "ra_deg": 346.190889, "dec_deg": 15.205833, "source": "Hipparcos", "fact": "Markab marks the southwest corner of the Great Square of Pegasus."},
    {"name": "Scheat", "ra_deg": 345.943573, "dec_deg": 28.082828, "source": "Hipparcos", "fact": "Scheat is a semiregular variable red giant in the Great Square of Pegasus."},
    {"name": "Algenib", "ra_deg": 15.183392, "dec_deg": 15.183609, "source": "Hipparcos", "fact": "Algenib is the southeast corner star of the Great Square of Pegasus."},
    {"name": "Enif", "ra_deg": 33.247241, "dec_deg": 10.613278, "source": "Hipparcos", "fact": "Enif (Epsilon Pegasi) is a red supergiant marking the nose of the Winged Horse."},
    {"name": "Almach", "ra_deg": 30.974764, "dec_deg": 42.329673, "source": "Hipparcos", "fact": "Almach is a celebrated gold-and-blue double star in Andromeda."},
    {"name": "Menkalinan", "ra_deg": 89.882303, "dec_deg": 54.284651, "source": "Hipparcos", "fact": "Menkalinan (Beta Aurigae) is an eclipsing binary in the Charioteer."},
    {"name": "Alphekka", "ra_deg": 233.671954, "dec_deg": 26.182961, "source": "Hipparcos", "fact": "Alphekka (Alpha Coronae Borealis) is the jewel of the Northern Crown."},
    {"name": "Rasalhague", "ra_deg": 263.733529, "dec_deg": 12.560037, "source": "Hipparcos", "fact": "Rasalhague is the brightest star in Ophiuchus, the Serpent Bearer."},
    {"name": "Kochab", "ra_deg": 222.676333, "dec_deg": 74.155493, "source": "Hipparcos", "fact": "Kochab was one of the historical 'guardians of the pole' before Polaris dominated."},
    {"name": "Nunki", "ra_deg": 283.816614, "dec_deg": -26.296809, "source": "Hipparcos", "fact": "Nunki (Sigma Sagittarii) is a B giant near the handle of the Teapot asterism."},
    {"name": "Peacock", "ra_deg": 306.411903, "dec_deg": -56.735088, "source": "Hipparcos", "fact": "Peacock (Alpha Pavonis) is a bright B star in the southern constellation Pavo."},
    {"name": "Albireo", "ra_deg": 62.304073, "dec_deg": 27.733528, "source": "Hipparcos", "fact": "Albireo (Beta Cygni) is a showpiece gold-and-blue double for small telescopes."},
    {"name": "Dschubba", "ra_deg": 240.082656, "dec_deg": -22.621688, "source": "Hipparcos", "fact": "Dschubba (Delta Scorpii) is a variable star near Antares in Scorpius."},
    {"name": "Avior", "ra_deg": 160.739249, "dec_deg": -59.514467, "source": "Hipparcos", "fact": "Avior (Epsilon Carinae) is a binary system in Carina and a southern navigation star."},
    {"name": "Suhail", "ra_deg": 139.272529, "dec_deg": -43.432589, "source": "Hipparcos", "fact": "Suhail (Lambda Velorum) is a K supergiant in Vela, bright along the Milky Way."},
    {"name": "Aspidiske", "ra_deg": 161.692417, "dec_deg": -59.432131, "source": "Hipparcos", "fact": "Aspidiske (Iota Carinae) is a luminous supergiant in the Carina Nebula region."},
    {"name": "Saiph", "ra_deg": 86.939101, "dec_deg": -9.669605, "source": "Hipparcos", "fact": "Saiph is Orion's eastern 'knee' star, a hot B supergiant like Rigel's kin."},
    {"name": "Mintaka", "ra_deg": 83.001667, "dec_deg": -0.299095, "source": "Hipparcos", "fact": "Mintaka is the westernmost belt star in Orion, nearly on the celestial equator."},
    {"name": "Alpheratz", "ra_deg": 2.096942, "dec_deg": 29.090431, "source": "Hipparcos", "fact": "Alpheratz is the brightest star in Andromeda and historically also Alpha Pegasi."},
    {"name": "Mirfak", "ra_deg": 51.080761, "dec_deg": 49.861269, "source": "Hipparcos", "fact": "Mirfak (Alpha Persei) anchors the Perseus OB association and is a supergiant."},
    {"name": "Murzim", "ra_deg": 95.6749475, "dec_deg": -17.95591658, "source": "Hipparcos", "fact": "Murzim (Beta Canis Majoris) is a bright B star near Sirius in Canis Major."},
    {"name": "Algieba", "ra_deg": 148.190554, "dec_deg": 19.840999, "source": "Hipparcos", "fact": "Algieba (Gamma Leonis) is a famous orange-giant binary in the Sickle of Leo."},
    {"name": "Zubenelgenubi", "ra_deg": 222.71963908, "dec_deg": -16.04177696, "source": "Hipparcos", "fact": "Zubenelgenubi (Alpha Librae) is the brighter of Libra's scales and a wide visual double."},
    {"name": "Zubeneschamali", "ra_deg": 229.250785, "dec_deg": -9.382778, "source": "Hipparcos", "fact": "Zubeneschamali (Beta Librae) is often noted for a subtle greenish tint."},
    {"name": "Unukalhai", "ra_deg": 218.07016284, "dec_deg": 6.5397743, "source": "Hipparcos", "fact": "Unukalhai (Alpha Serpentis) is the brightest star in the head of Serpens."},
    {"name": "Kaus Australis", "ra_deg": 276.042993, "dec_deg": -34.384616, "source": "Hipparcos", "fact": "Kaus Australis (Epsilon Sagittarii) marks the lid of the Teapot in Sagittarius."},
    {"name": "Acrab", "ra_deg": 241.36006841, "dec_deg": -19.73849352, "source": "Hipparcos", "fact": "Acrab (Beta Scorpii) is a fine telescopic multiple in the head of Scorpius."},
    {"name": "Rukbat", "ra_deg": 283.80188104, "dec_deg": -30.39420109, "source": "Hipparcos", "fact": "Rukbat (Alpha Sagittarii) marks the archer's knee in Sagittarius."},
    {"name": "Tarazed", "ra_deg": 297.75684735, "dec_deg": 10.41572455, "source": "Hipparcos", "fact": "Tarazed (Gamma Aquilae) is an orange giant near Altair in the Eagle."},
    {"name": "Sadalmelik", "ra_deg": 331.44598271, "dec_deg": -0.31984929, "source": "Hipparcos", "fact": "Sadalmelik (Alpha Aquarii) is a G supergiant in the Water Bearer."},
    {"name": "Sadalsuud", "ra_deg": 322.80058415, "dec_deg": -25.71219882, "source": "Hipparcos", "fact": "Sadalsuud (Beta Aquarii) is a yellow supergiant in Aquarius."},
    {"name": "Algedi", "ra_deg": 291.52602091, "dec_deg": -22.45397832, "source": "Hipparcos", "fact": "Algedi (Alpha Capricorni) is an optical wide pair — a classic binocular sight."},
    {"name": "Denebola", "ra_deg": 177.264861, "dec_deg": 14.571944, "source": "Hipparcos", "fact": "Denebola is the tail of Leo and a nearby A-type star with a debris disk."},
    {"name": "Alcor", "ra_deg": 201.3064015, "dec_deg": 54.98795585, "source": "Hipparcos", "fact": "Alcor rides with Mizar and was historically used as an eyesight test star."},
]
